---
  - name: Aide Install RHEL
    yum:
     name: aide
     state: present
    when: ansible_facts["pkg_mgr"] == "yum" or ansible_facts["pkg_mgr"] == "dnf"

  - name: Aide Install Deb
    apt:
     name: aide
     state: present
    when: ansible_facts["pkg_mgr"] == "apt"

  - name: Aide Install SLES
    zypper:
     name: aide
     state: present
    when: ansible_facts["pkg_mgr"] == "zypper"
    
  - name: Aide Path Check
    shell:
     cmd: which aide
    register: whichaide
    
  - name: Aide Database init SLES
    shell:
     cmd: {{ whichaide.stdout }} -i
    when: aide_init_first == "yes" and ansible_facts["pkg_mgr"] == "zypper"
  
  - name: Aide Database Changed
    copy:
     src: /var/lib/aide/aide.db.new
     dest: /var/lib/aide/aide.db
    when: ansible_facts["pkg_mgr"] == "zypper" or ansible_facts["pkg_mgr"] == "apt"

- name: Aide Database init Debian & Ubuntu
    shell:
     cmd: {{ whichaide.stdout }} -c /etc/aide/aide.conf --init
    when: aide_init_first == "yes" and ansible_facts["pkg_mgr"] == "apt"

  - name: Aide Database init RHEL
    shell:
     cmd: {{ whichaide.stdout }} --init
    when: aide_init_first == "yes" and ansible_facts["pkg_mgr"] == "yum" or  ansible_facts["pkg_mgr"] == "dnf"

  - name: Aide Database Change
    copy:
     src: /var/lib/aide/aide.db.new.gz
     dest: /var/lib/aide/aide.db.gz
    when: ansible_facts["pkg_mgr"] == "yum" or  ansible_facts["pkg_mgr"] == "dnf"
    
  - name: Aide Cron job
    import_tasks: cron-create.yml
    when: aidecron_remote == "yes"
...
